doc-warnings: false
test-warnings: true
strictness: veryhigh
max-line-length: 120
uses:
  - flask
autodetect: true
ignore-paths:
  - postman
  - lib
  - appguard_ci/docs
  - appguard_ci/docker_appguard_ci
python-targets:
  - 3