
# In Order to Run Docker in interactive mode just change command (un-comment command on line 14 and
# comment line 18
# After saving changes in cur dir execute command:
# docker-compose run --rm magen_ingestion

# Since docker-compose version 2 'links' key-word is obsolete and 'networks' is preferable approach
# Although 'links' and 'depends_on' make sure to start linked containers before the main one
# docker-compose forces links to be launched and returns an error if linked container is already launched

version: "2"
services:
  appguard_ci_service:
    build: .
    image: appguard_ci_service:v1.0
    container_name: magen_ingestion
    command: python3 ./appguard_ci_server/appguard_ci_server.py --console-log-level 'info' --log-dir 'appguard_ci_logs' 2>&1 >> server.log
    # command: /bin/bash
    ports:
      - "6020:6020"
    volumes:
      - ~/magen_data/ingestion/:/opt/data/
      - ../..:/opt/server
    stdin_open: true
    tty: true
    networks:
      - default

networks:
  default:
    external:
      name: appguard_ci_net
